/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ContactMessage {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface Order {
  'paymentStatus' : { 'pending' : null } |
    { 'paid' : null } |
    { 'failed' : null },
  'paymentMethod' : { 'cod' : null } |
    { 'stripe' : null },
  'userId' : Principal,
  'createdAt' : bigint,
  'deliveryStatus' : { 'shipped' : null } |
    { 'outForDelivery' : null } |
    { 'delivered' : null } |
    { 'confirmed' : null } |
    { 'processing' : null },
  'totalAmount' : bigint,
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'priceAtPurchase' : bigint,
}
export interface Product {
  'name' : string,
  'description' : string,
  'deliveryType' : { 'twoHours' : null } |
    { 'twoDays' : null },
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProduct' : ActorMethod<[Product], bigint>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [{ 'cod' : null } | { 'stripe' : null }, [] | [string]],
    bigint
  >,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitMessage' : ActorMethod<[string, string, string], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateDeliveryStatus' : ActorMethod<
    [
      bigint,
      { 'shipped' : null } |
        { 'outForDelivery' : null } |
        { 'delivered' : null } |
        { 'confirmed' : null } |
        { 'processing' : null },
    ],
    undefined
  >,
  'updatePaymentStatus' : ActorMethod<
    [bigint, { 'pending' : null } | { 'paid' : null } | { 'failed' : null }],
    undefined
  >,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];