/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderItem {
    productId: bigint;
    quantity: bigint;
    priceAtPurchase: bigint;
}
export interface Order {
    paymentStatus: Variant_pending_paid_failed;
    paymentMethod: Variant_cod_stripe;
    userId: Principal;
    createdAt: bigint;
    deliveryStatus: Variant_shipped_outForDelivery_delivered_confirmed_processing;
    totalAmount: bigint;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ContactMessage {
    name: string;
    createdAt: bigint;
    email: string;
    message: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
}
export interface Product {
    name: string;
    description: string;
    deliveryType: Variant_twoHours_twoDays;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: string;
    price: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cod_stripe {
    cod = "cod",
    stripe = "stripe"
}
export enum Variant_pending_paid_failed {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum Variant_shipped_outForDelivery_delivered_confirmed_processing {
    shipped = "shipped",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed",
    processing = "processing"
}
export enum Variant_twoHours_twoDays {
    twoHours = "twoHours",
    twoDays = "twoDays"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToCart(productId: bigint, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createProduct(p: Product): Promise<bigint>;
    deleteProduct(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getContactMessages(): Promise<Array<ContactMessage>>;
    getOrder(id: bigint): Promise<Order>;
    getOrders(): Promise<Array<Order>>;
    getProduct(id: bigint): Promise<Product>;
    getProducts(): Promise<Array<Product>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    placeOrder(paymentMethod: Variant_cod_stripe, stripePaymentIntentId: string | null): Promise<bigint>;
    removeFromCart(productId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitMessage(name: string, email: string, message: string): Promise<bigint>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateDeliveryStatus(orderId: bigint, status: Variant_shipped_outForDelivery_delivered_confirmed_processing): Promise<void>;
    updatePaymentStatus(orderId: bigint, status: Variant_pending_paid_failed): Promise<void>;
    updateProduct(id: bigint, p: Product): Promise<void>;
}
import type { Order as _Order, OrderItem as _OrderItem, Product as _Product, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_Product_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_Product_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessages();
            return result;
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async placeOrder(arg0: Variant_cod_stripe, arg1: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_variant_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_variant_n23(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async removeFromCart(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitMessage(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateDeliveryStatus(arg0: bigint, arg1: Variant_shipped_outForDelivery_delivered_confirmed_processing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_variant_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_variant_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: Variant_pending_paid_failed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_Product_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_Product_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Order_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus: {
        pending: null;
    } | {
        paid: null;
    } | {
        failed: null;
    };
    paymentMethod: {
        cod: null;
    } | {
        stripe: null;
    };
    userId: Principal;
    createdAt: bigint;
    deliveryStatus: {
        shipped: null;
    } | {
        outForDelivery: null;
    } | {
        delivered: null;
    } | {
        confirmed: null;
    } | {
        processing: null;
    };
    totalAmount: bigint;
    stripePaymentIntentId: [] | [string];
    items: Array<_OrderItem>;
}): {
    paymentStatus: Variant_pending_paid_failed;
    paymentMethod: Variant_cod_stripe;
    userId: Principal;
    createdAt: bigint;
    deliveryStatus: Variant_shipped_outForDelivery_delivered_confirmed_processing;
    totalAmount: bigint;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
} {
    return {
        paymentStatus: from_candid_variant_n11(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_variant_n12(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        createdAt: value.createdAt,
        deliveryStatus: from_candid_variant_n13(_uploadFile, _downloadFile, value.deliveryStatus),
        totalAmount: value.totalAmount,
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        items: value.items
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    deliveryType: {
        twoHours: null;
    } | {
        twoDays: null;
    };
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: string;
    price: bigint;
}): {
    name: string;
    description: string;
    deliveryType: Variant_twoHours_twoDays;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        deliveryType: from_candid_variant_n18(_uploadFile, _downloadFile, value.deliveryType),
        isActive: value.isActive,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: value.category,
        price: value.price
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): Variant_pending_paid_failed {
    return "pending" in value ? Variant_pending_paid_failed.pending : "paid" in value ? Variant_pending_paid_failed.paid : "failed" in value ? Variant_pending_paid_failed.failed : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    stripe: null;
}): Variant_cod_stripe {
    return "cod" in value ? Variant_cod_stripe.cod : "stripe" in value ? Variant_cod_stripe.stripe : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
}): Variant_shipped_outForDelivery_delivered_confirmed_processing {
    return "shipped" in value ? Variant_shipped_outForDelivery_delivered_confirmed_processing.shipped : "outForDelivery" in value ? Variant_shipped_outForDelivery_delivered_confirmed_processing.outForDelivery : "delivered" in value ? Variant_shipped_outForDelivery_delivered_confirmed_processing.delivered : "confirmed" in value ? Variant_shipped_outForDelivery_delivered_confirmed_processing.confirmed : "processing" in value ? Variant_shipped_outForDelivery_delivered_confirmed_processing.processing : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    twoHours: null;
} | {
    twoDays: null;
}): Variant_twoHours_twoDays {
    return "twoHours" in value ? Variant_twoHours_twoDays.twoHours : "twoDays" in value ? Variant_twoHours_twoDays.twoDays : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n22(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Product_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    deliveryType: Variant_twoHours_twoDays;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: string;
    price: bigint;
}): {
    name: string;
    description: string;
    deliveryType: {
        twoHours: null;
    } | {
        twoDays: null;
    };
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: string;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        deliveryType: to_candid_variant_n5(_uploadFile, _downloadFile, value.deliveryType),
        isActive: value.isActive,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: value.category,
        price: value.price
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cod_stripe): {
    cod: null;
} | {
    stripe: null;
} {
    return value == Variant_cod_stripe.cod ? {
        cod: null
    } : value == Variant_cod_stripe.stripe ? {
        stripe: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_shipped_outForDelivery_delivered_confirmed_processing): {
    shipped: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
} {
    return value == Variant_shipped_outForDelivery_delivered_confirmed_processing.shipped ? {
        shipped: null
    } : value == Variant_shipped_outForDelivery_delivered_confirmed_processing.outForDelivery ? {
        outForDelivery: null
    } : value == Variant_shipped_outForDelivery_delivered_confirmed_processing.delivered ? {
        delivered: null
    } : value == Variant_shipped_outForDelivery_delivered_confirmed_processing.confirmed ? {
        confirmed: null
    } : value == Variant_shipped_outForDelivery_delivered_confirmed_processing.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_paid_failed): {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
} {
    return value == Variant_pending_paid_failed.pending ? {
        pending: null
    } : value == Variant_pending_paid_failed.paid ? {
        paid: null
    } : value == Variant_pending_paid_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_twoHours_twoDays): {
    twoHours: null;
} | {
    twoDays: null;
} {
    return value == Variant_twoHours_twoDays.twoHours ? {
        twoHours: null
    } : value == Variant_twoHours_twoDays.twoDays ? {
        twoDays: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
